# Generated by Django 2.2.7 on 2020-03-23 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_student_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('telepone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('1', 'Fruits'), ('2', 'Vegetables'), ('3', 'Dairy')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_helper',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_nurse',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
